# http://about.travis-ci.org/docs/user/build-configuration/
before_install: 'gem update --system'
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
notifications:
  irc: "irc.freenode.org#padrino"
  recipients:
    - info@daddye.it
    - nesquena@gmail.com
    - mr.arthur.chiu@gmail.com
    - joshbuddy@gmail.com
    - florian.gilcher@asquera.de
